apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosysdig-test
  namespace: cxb-cluhea-pre
spec:
  selector:
    matchLabels:
      app: gosysdig
  replicas: 1
  template:
    metadata:
      labels:
        app: gosysdig
    spec:
      containers:
        - name: gosysdig
          image: docker-registry.cloud.caixabank.com/containers/bchicp/gosysdig:0.0.0
          resources:
            limits:
              cpu: "0.05"
              memory: 384Mi
            requests:
              cpu: "0.025"
              memory: 64Mi
          securityContext:
            capabilities:
              drop: ["KILL", "SETGID", "SETGID", "SETUID"]
      imagePullSecrets:
        - name: registry
      #automountServiceAccountToken: false
    serviceAccountName: cluster-health  